// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCoalescingLock is an autogenerated mock type for the CoalescingLock type
type MockCoalescingLock struct {
	mock.Mock
}

type MockCoalescingLock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCoalescingLock) EXPECT() *MockCoalescingLock_Expecter {
	return &MockCoalescingLock_Expecter{mock: &_m.Mock}
}

// AcquireLock provides a mock function with given fields: ctx, resource
func (_m *MockCoalescingLock) AcquireLock(ctx context.Context, resource string) (bool, error) {
	ret := _m.Called(ctx, resource)

	if len(ret) == 0 {
		panic("no return value specified for AcquireLock")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, resource)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, resource)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, resource)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCoalescingLock_AcquireLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireLock'
type MockCoalescingLock_AcquireLock_Call struct {
	*mock.Call
}

// AcquireLock is a helper method to define mock.On call
//   - ctx context.Context
//   - resource string
func (_e *MockCoalescingLock_Expecter) AcquireLock(ctx interface{}, resource interface{}) *MockCoalescingLock_AcquireLock_Call {
	return &MockCoalescingLock_AcquireLock_Call{Call: _e.mock.On("AcquireLock", ctx, resource)}
}

func (_c *MockCoalescingLock_AcquireLock_Call) Run(run func(ctx context.Context, resource string)) *MockCoalescingLock_AcquireLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCoalescingLock_AcquireLock_Call) Return(_a0 bool, _a1 error) *MockCoalescingLock_AcquireLock_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCoalescingLock_AcquireLock_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockCoalescingLock_AcquireLock_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseLock provides a mock function with given fields: ctx, resource
func (_m *MockCoalescingLock) ReleaseLock(ctx context.Context, resource string) error {
	ret := _m.Called(ctx, resource)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, resource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCoalescingLock_ReleaseLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseLock'
type MockCoalescingLock_ReleaseLock_Call struct {
	*mock.Call
}

// ReleaseLock is a helper method to define mock.On call
//   - ctx context.Context
//   - resource string
func (_e *MockCoalescingLock_Expecter) ReleaseLock(ctx interface{}, resource interface{}) *MockCoalescingLock_ReleaseLock_Call {
	return &MockCoalescingLock_ReleaseLock_Call{Call: _e.mock.On("ReleaseLock", ctx, resource)}
}

func (_c *MockCoalescingLock_ReleaseLock_Call) Run(run func(ctx context.Context, resource string)) *MockCoalescingLock_ReleaseLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCoalescingLock_ReleaseLock_Call) Return(_a0 error) *MockCoalescingLock_ReleaseLock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCoalescingLock_ReleaseLock_Call) RunAndReturn(run func(context.Context, string) error) *MockCoalescingLock_ReleaseLock_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForLock provides a mock function with given fields: ctx, resource
func (_m *MockCoalescingLock) WaitForLock(ctx context.Context, resource string) error {
	ret := _m.Called(ctx, resource)

	if len(ret) == 0 {
		panic("no return value specified for WaitForLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, resource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCoalescingLock_WaitForLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForLock'
type MockCoalescingLock_WaitForLock_Call struct {
	*mock.Call
}

// WaitForLock is a helper method to define mock.On call
//   - ctx context.Context
//   - resource string
func (_e *MockCoalescingLock_Expecter) WaitForLock(ctx interface{}, resource interface{}) *MockCoalescingLock_WaitForLock_Call {
	return &MockCoalescingLock_WaitForLock_Call{Call: _e.mock.On("WaitForLock", ctx, resource)}
}

func (_c *MockCoalescingLock_WaitForLock_Call) Run(run func(ctx context.Context, resource string)) *MockCoalescingLock_WaitForLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCoalescingLock_WaitForLock_Call) Return(_a0 error) *MockCoalescingLock_WaitForLock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCoalescingLock_WaitForLock_Call) RunAndReturn(run func(context.Context, string) error) *MockCoalescingLock_WaitForLock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCoalescingLock creates a new instance of MockCoalescingLock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCoalescingLock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCoalescingLock {
	mock := &MockCoalescingLock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
