// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRequestCache is an autogenerated mock type for the RequestCache type
type MockRequestCache struct {
	mock.Mock
}

type MockRequestCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRequestCache) EXPECT() *MockRequestCache_Expecter {
	return &MockRequestCache_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockRequestCache) Get(ctx context.Context, key string) (interface{}, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interface{}, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interface{}); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRequestCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRequestCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockRequestCache_Expecter) Get(ctx interface{}, key interface{}) *MockRequestCache_Get_Call {
	return &MockRequestCache_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockRequestCache_Get_Call) Run(run func(ctx context.Context, key string)) *MockRequestCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRequestCache_Get_Call) Return(_a0 interface{}, _a1 error) *MockRequestCache_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRequestCache_Get_Call) RunAndReturn(run func(context.Context, string) (interface{}, error)) *MockRequestCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, ttl
func (_m *MockRequestCache) Set(ctx context.Context, key string, value interface{}, ttl time.Duration) error {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRequestCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRequestCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - ttl time.Duration
func (_e *MockRequestCache_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *MockRequestCache_Set_Call {
	return &MockRequestCache_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *MockRequestCache_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, ttl time.Duration)) *MockRequestCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockRequestCache_Set_Call) Return(_a0 error) *MockRequestCache_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRequestCache_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *MockRequestCache_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRequestCache creates a new instance of MockRequestCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRequestCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRequestCache {
	mock := &MockRequestCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
